### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by workingjubilee** [PhantomOS/PhantomOS#14]
The "Phantom OS" name has been done before:
- http://phantomos.org/
- https://www.theregister.com/2009/02/03/phantom_russian_os/
- https://github.com/dzavalishin/phantomuserland

I thought I should mention it before you get much further, so you can be aware that your work may wind up easily confounded with works primarily by people from another nation-state. Upstanding people, I'm sure, or at least, have no reason to doubt. But the locale is likewise exceptional in some regards, considering the events of 2022.

**Comment by chorman0773** [comment]
We are aware of it. Unfortunately, as you can imagine, coming up with a
substitute name is not an easy or quick task.

**Comment by workingjubilee** [comment]
I certainly do not envy you, no.

**Comment by rdrpenguin04** [comment]
There was a time when we were fairly certain that the Russian Phantom OS would not be problematic. Now, it seems to be actually getting noticed, and it is an interesting concept. While I do not think the Russian origin is of any particular concern (after all, plenty of good things come out of Russia, and given my own nation of origin, I'm not one to judge a nation on the basis of its government), the existence of another novel OS with the same name as ours is definitely a problem.

As it is, this OS should definitely change its name. We're open to any ideas.

**Comment by rdrpenguin04** [comment]
The Discord community has decided on Lilium as a replacement. We will start migrating the names shortly.

**Comment by rdrpenguin04** [comment]
Rename is complete in the organization and all repositories; closing this issue.
